name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '24.0.5'
        elixir-version: '1.12.2'
    - name: Install dependencies
      run: mix deps.get
    - name: Run formatter
      run: mix format --check-formatted
    - name: Build
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
